### ISSUE TITLE
Problem Configuring "Content Delivery"

### ISSUE THREAD

**Issue by danteciambella** [Sitecore/Sitecore-Configuration-Roles#14]
Hey Alen when I try to configure the ContentDelivery I have the following:

**Server Error in '/' Application.
Could not get pipeline: speak.client.getStyle (domain: )**

When I try to click on the button on the hight left corner with Desktop Sitecore View.
What I'm missing?

**Comment by AlenPelin** [comment]
@danteciambella could you include the screenshot?

**Comment by danteciambella** [comment]
![speak_error](https://user-images.githubusercontent.com/19855426/27533936-9cd5a094-5a65-11e7-8b26-2e62a0f7589d.png)

**Comment by danteciambella** [comment]
@AlenPelin I soved but I'm not sure adding the OR ContentDelivery to 001.Sitecore.Speak.Important.config file. Another question why using ContentDelivery the default view is Always Desktop?

**Comment by AlenPelin** [comment]
Thanks for confirmation. ContentDelivery instance does not officially support logging in to Sitecore Client - it is recommended to restrict access to the appropriate folders in IIS.
