### ISSUE TITLE
Config Error

### ISSUE THREAD

**Issue by hetaldave** [Sitecore/Sitecore-Configuration-Roles#16]
Hello,
I followed the steps on a vanilla Sitecore install as well as also tried to install CM role using SIM QA application. I get the following error. What am I doing wrong?
![2017-07-17_9-57-57](https://user-images.githubusercontent.com/8376501/28271449-7f810386-6ad6-11e7-9578-0a17dde4156a.png)

![2017-07-17_9-59-45](https://user-images.githubusercontent.com/8376501/28271517-ba2a9326-6ad6-11e7-8850-18514dce3d8a.png)

**Comment by AlenPelin** [comment]
Thanks for reporting the issue. It appeared it is only actual for 8.1.3, 8.2.0, 8.2.1.

Fixed by a6b8f4c, bbaa24e, f7353e5

In order to get a fix just delete and install the instance again.
