### ISSUE TITLE
ReportingServiceUrl.config

### ISSUE THREAD

**Issue by hetaldave** [Sitecore/Sitecore-Configuration-Roles#17]
The lines 3-7 in the file needs to be commented out. Otherwise you get the error below - 

![2017-07-19_13-09-37](https://user-images.githubusercontent.com/8376501/28379950-8ef36422-6c83-11e7-8626-c747f09e70cf.png)

**Comment by AlenPelin** [comment]
No, it is by design. You must open this file and follow the comments.
