### ISSUE TITLE
Configuration files for Sitecore 8.2 update 6

### ISSUE THREAD

**Issue by dahla** [Sitecore/Sitecore-Configuration-Roles#20]
Do you have plans for updating the configuration files for Sitecore 8.2 update 6?

**Comment by sebastiantecsi** [comment]
I've made fork and added a new branch for the configurations for Sitecore 8.2 update 6 here https://github.com/sebastiantecsi/Sitecore-Configuration-Roles/tree/configuration/8.2.6 but it seems that I can not make a pull request. @AlenPelin maybe you can help on this matter and also validate my changes too.

**Comment by AlenPelin** [comment]
I will get back to you next week.

**Comment by AlenPelin** [comment]
Fixed by Sitecore/Sitecore-Configuration-Roles@0820a6a69e1259e2ae0384a1c5766cd4d79e7cb4
