### ISSUE TITLE
Sitecore 8.2 Update 3 Some issue with WFFM

### ISSUE THREAD

**Issue by danteciambella** [Sitecore/Sitecore-Configuration-Roles#21]
Sitecore suggested to use the Configuration Role for installing new Sitecore instance. 
We used the "Configuration Role" for 8.2 Update 3 version and now we installed the WFFM module.
The production environment is built on CM + CD1 + CD2. 
When we publish the form and try to reach it by URL into the browser we have the following issue:
**Could not find configuration node: databases/database[@id='master']** 
Is it possible that the problem is related with the Configuration Role? 
If yes can you help us to solve the problem? We are in production environment and we need the WFFM up and running.
Seems that the problem is on the file **https://github.com/Sitecore/Sitecore-Configuration-Roles/blob/configuration/8.2.3/App_Config/Include/Sitecore.Marketing.config**
Where also for Content Delivery the <itemRepositoriesDatabase> is set to master.
Please can you give a feedback?

**Comment by AlenPelin** [comment]
Yes, it is possible. This module does not support WFFM out of the box - you need to annotate WFFM configuration files yourself to make them work altogether.

This is not officially supported, but you still can request assistance via support portal. They might not say how exactly to tune configuration roles, but can point you to right direction.
