### ISSUE TITLE
How to Upgrade from Sitecore 8.2 Update 3 to Sitecore 8.2 Update 6

### ISSUE THREAD

**Issue by danteciambella** [Sitecore/Sitecore-Configuration-Roles#22]
I have a question, the customer is asking us to upgrade Sitecore from the Sitecore 8.2 Update 3 to Sitecore 8.2 Update 6 version. How can we procede using the Configuration Role? 
The architecture is built on CM + CD1 +CD2. What's the best way to procede?

Regards.

**Comment by AlenPelin** [comment]
Using configuration roles does not make any difference apart from extra step to install newer version of configuration files annotated with configuration roles from this repository.
