### ISSUE TITLE
Supported Sitecore Version

### ISSUE THREAD

**Issue by sebastiantecsi** [Sitecore/Sitecore-Configuration-Roles#7]
Hi there, 

In readme its written in **Prerequsites** that supports **Sitecore CMS 8.2 - all releases**, but when I read a bit further down its written that works for **Sitecore 8.2 Update-2** and **Sitecore 8.2 Update-3**.
What about **Sitecore 8.2 Update-1**? Is it supported ? Can I have it somehow running in this **Sitecore 8.2 Update-1** ? 

Thank you,
Sebastian

**Comment by AlenPelin** [comment]
Hi @sebastiantecsi 

Thanks for your feedback. That's right, all releases of 8.2 are supported by the new configuration engine. However the annotated configuration files were available only for 8.2 Update-2 and Update-3 as nobody requested Update-1 and Initial Release before. 

As you requested these files, I prepared them for you, check readme again - and I've also updated SIM QA to support them.

**Comment by sebastiantecsi** [comment]
Hello,

Thank you for the response and the updated files.

Sebastian
